[font]
size = 11
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
offset = { x = -1, y = -2 }

[window]
padding = { x = 10, y = 15 } 
dynamic_title = true

[colors.primary]
background = "#0B0E14"
foreground = "#b3b1ad"
